parameters:
  melifaro_booking.entity_class: ~

services:
  booker:
    class: Melifaro\BookingBundle\Helper\Booking
    arguments: [%melifaro_booking.entity_class%, @doctrine]

  booking_calendar:
    class: Melifaro\BookingBundle\Twig\CalendarExtension
    arguments: [%melifaro_booking.entity_class%, @doctrine]
    tags:
      - {name: twig.extension}
